create table if not exists public.app_governance (
  user_id uuid primary key references public.profiles(id) on delete restrict,
  governance_role text not null check (governance_role in ('OWNER','ADMIN')),
  created_at timestamptz not null default now(),
  created_by uuid null,
  updated_at timestamptz not null default now()
);

create unique index if not exists app_governance_single_owner_idx
  on public.app_governance ((governance_role))
  where governance_role = 'OWNER';

create table if not exists public.access_governance_audit (
  id bigint generated by default as identity primary key,
  actor_id uuid null,
  actor_email text null,
  target_id uuid not null,
  action text not null,
  previous_role text null,
  new_role text null,
  created_at timestamptz not null default now()
);

alter table public.app_governance enable row level security;
alter table public.access_governance_audit enable row level security;

revoke all on table public.app_governance from anon, authenticated;
revoke all on table public.access_governance_audit from anon, authenticated;
grant select on table public.app_governance to authenticated;
grant select on table public.access_governance_audit to authenticated;

create or replace function private.is_forecast_owner()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.app_governance g
    join public.profiles p on p.id = g.user_id
    where g.user_id = (select auth.uid())
      and g.governance_role = 'OWNER'
      and p.ativo = true
  );
$$;

create or replace function private.is_forecast_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.app_governance g
    join public.profiles p on p.id = g.user_id
    where g.user_id = (select auth.uid())
      and g.governance_role in ('OWNER','ADMIN')
      and p.ativo = true
  );
$$;

revoke all on function private.is_forecast_owner() from public, anon;
revoke all on function private.is_forecast_admin() from public, anon;
grant execute on function private.is_forecast_owner() to authenticated;
grant execute on function private.is_forecast_admin() to authenticated;

drop policy if exists app_governance_select_self_or_owner on public.app_governance;
create policy app_governance_select_self_or_owner
  on public.app_governance for select to authenticated
  using (user_id = (select auth.uid()) or (select private.is_forecast_owner()));

drop policy if exists access_governance_audit_owner_select on public.access_governance_audit;
create policy access_governance_audit_owner_select
  on public.access_governance_audit for select to authenticated
  using ((select private.is_forecast_owner()));

create or replace function public.list_forecast_access_users()
returns table (
  user_id uuid,
  email text,
  nome text,
  ativo boolean,
  perfil_funcional text,
  governance_role text
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    p.id,
    u.email::text,
    p.nome,
    p.ativo,
    p.perfil,
    coalesce(g.governance_role, 'USER')
  from public.profiles p
  join auth.users u on u.id = p.id
  left join public.app_governance g on g.user_id = p.id
  where (select private.is_forecast_owner())
  order by case coalesce(g.governance_role,'USER') when 'OWNER' then 0 when 'ADMIN' then 1 else 2 end, p.nome;
$$;

revoke all on function public.list_forecast_access_users() from public, anon;
grant execute on function public.list_forecast_access_users() to authenticated;

create or replace function public.set_forecast_admin_role(p_target_id uuid, p_make_admin boolean)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_email text;
  v_previous_role text;
  v_target_exists boolean;
begin
  if not (select private.is_forecast_owner()) then
    raise exception 'OWNER_REQUIRED';
  end if;

  select email::text into v_actor_email from auth.users where id = (select auth.uid());
  select exists(select 1 from public.profiles where id = p_target_id) into v_target_exists;
  if not v_target_exists then
    raise exception 'TARGET_NOT_FOUND';
  end if;

  select governance_role into v_previous_role
  from public.app_governance
  where user_id = p_target_id;

  if v_previous_role = 'OWNER' then
    raise exception 'OWNER_IMMUTABLE';
  end if;

  if p_make_admin then
    insert into public.app_governance(user_id, governance_role, created_by, updated_at)
    values (p_target_id, 'ADMIN', (select auth.uid()), now())
    on conflict (user_id) do update
      set governance_role = 'ADMIN', updated_at = now();

    -- Compatibilidade da UI legada: o App ainda usa profiles.perfil para
    -- mostrar os controles de Parâmetros. A autorização real está em app_governance.
    update public.profiles
    set perfil = 'admin'
    where id = p_target_id;
  else
    delete from public.app_governance
    where user_id = p_target_id and governance_role = 'ADMIN';

    update public.profiles
    set perfil = 'usuario'
    where id = p_target_id;
  end if;

  insert into public.access_governance_audit(
    actor_id, actor_email, target_id, action, previous_role, new_role
  ) values (
    (select auth.uid()),
    v_actor_email,
    p_target_id,
    case when p_make_admin then 'GRANT_ADMIN' else 'REVOKE_ADMIN' end,
    coalesce(v_previous_role,'USER'),
    case when p_make_admin then 'ADMIN' else 'USER' end
  );
end;
$$;

revoke all on function public.set_forecast_admin_role(uuid, boolean) from public, anon;
grant execute on function public.set_forecast_admin_role(uuid, boolean) to authenticated;

-- Provisiona o Owner sem hardcode de UUID gerado.
insert into public.app_governance(user_id, governance_role, created_by)
select p.id, 'OWNER', p.id
from public.profiles p
join auth.users u on u.id = p.id
where lower(u.email) = lower('filipecarneirodasilva@gmail.com')
  and p.ativo = true
on conflict (user_id) do update set governance_role = 'OWNER', updated_at = now();

-- Preserva administradores existentes como delegados.
insert into public.app_governance(user_id, governance_role, created_by)
select p.id, 'ADMIN', owner_row.user_id
from public.profiles p
join auth.users u on u.id = p.id
cross join lateral (
  select user_id from public.app_governance where governance_role='OWNER' limit 1
) owner_row
where p.ativo = true
  and p.perfil = 'admin'
  and lower(u.email) <> lower('filipecarneirodasilva@gmail.com')
on conflict (user_id) do update
  set governance_role = case when public.app_governance.governance_role='OWNER' then 'OWNER' else 'ADMIN' end,
      updated_at = now();